name: release

on:
  release:
    types: [published]

jobs:
  cocoapods_push:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s '/Applications/Xcode_11.5.app/Contents/Developer'
      - run: pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}