name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-ios:
    strategy:
      matrix:
        xcode-version: [11.5, 10.3]
        include:
          - xcode-version: 11.5
            destination: "platform=iOS Simulator,OS=13.5,name=iPhone 11"
          - xcode-version: 10.3
            destination: "platform=iOS Simulator,OS=12.4,name=iPhone Xs Max"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Carthage Bootstrap
        run: carthage bootstrap --platform iOS
      - name: set -o pipefail
        run: set -o pipefail
      - name: test
        run: xcodebuild test -scheme "Nuke-WebP-Plugin iOS" -destination "${{ matrix.destination }}" -configuration Debug;