name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - goobye-travis-ci

jobs:
  test-ios:
    strategy:
      matrix:
        xcode-version: [11.5]
        include:
          - xcode-version: 11.5
            destination: "platform=iOS Simulator,OS=13.5,name=iPhone 11"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Carthage Bootstrap
        run: carthage bootstrap --platform iOS
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: set -o pipefail && xcodebuild test -scheme "Nuke-WebP-Plugin iOS" -destination "${{ matrix.destination }}" -configuration Debug | xcpretty -c

  test-macos:
    strategy:
      matrix:
        xcode-version: [11.5]
        include:
          - xcode-version: 11.5
            destination: "arch=x86_64"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Carthage Bootstrap
        run: carthage bootstrap --platform Mac
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: set -o pipefail && xcodebuild test -scheme "Nuke-WebP-Plugin macOS" -destination "${{ matrix.destination }}" -configuration Debug | xcpretty -c

  test-tvos:
    strategy:
      matrix:
        xcode-version: [11.5]
        include:
          - xcode-version: 11.5
            destination: "platform=tvOS Simulator,OS=13.4,name=Apple TV 4K"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Carthage Bootstrap
        run: carthage bootstrap --platform tvOS
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: set -o pipefail && xcodebuild test -scheme "Nuke-WebP-Plugin tvOS" -destination "${{ matrix.destination }}" -configuration Debug | xcpretty -c

  build-watchos:
    strategy:
      matrix:
        xcode-version: [11.5]
        include:
          - xcode-version: 11.5
            destination: "platform=watchOS Simulator,OS=6.2,name=Apple Watch Series 5 - 44mm"
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer'
      - name: Carthage Bootstrap
        run: carthage bootstrap --platform watchOS
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        run: set -o pipefail && xcodebuild test -scheme "Nuke-WebP-Plugin watchOS" -destination "${{ matrix.destination }}" -configuration Debug | xcpretty -c